#!/usr/bin/env python3
"""B154b: DIMACS graph loader + Max-k-Cut mapping.

DIMACS-format is de tweede standaard voor benchmark-grafen (naast Gset/BiqMac).
De implementatie-challenges voor graph coloring (DIMACS-challenge-II) gebruiken
het 'p edge' formaat; dezelfde grafen zijn via Max-k-Cut relevant.

Dit bestand levert:

  1. `parse_dimacs(filepath|text)`        — DIMACS edge-format parser
  2. `DIMACS_CHROMATIC`                   — kleine database van chromatische
                                             getallen voor bekende DIMACS-graven
  3. `max_k_cut_upper_bound(graph, k)`    — trivial OP-grens voor Max-k-Cut
  4. `dimacs_to_maxcut(graph, k, μ)`      — reductie Max-k-Cut → MaxCut via
                                             edge-gadget (Frieze-Jerrum)
  5. Kleine ingebouwde fixtures: myciel3, queen5_5, petersen-DIMACS, etc.

DIMACS edge-format (graph-coloring challenge):
    c  comment lines
    p edge N M           (problem line)
    e i j                (edge; 1-indexed)
    ...

Referenties:
  - Johnson & Trick (1996), DIMACS Implementation Challenge II
  - Frieze & Jerrum (1997), "Improved approximation algorithms for MAX k-CUT"
    Algorithmica 18, 67-81
  - Goemans-Williamson (1995), Ibid. voor k=2
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Iterable

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from rqaoa import WeightedGraph


# ============================================================
# 1. DIMACS parser
# ============================================================

def parse_dimacs(source: str, from_text: bool = False) -> tuple[WeightedGraph, int, int]:
    """Parse DIMACS edge-format.

    Lines:
      c comment
      p edge N M
      e i j           (1-indexed vertices)
      e i j w         (met edge-gewicht; niet standaard maar we accepteren het)

    Returns:
      (WeightedGraph, declared_n, declared_m)
    """
    if from_text:
        lines = source.strip().splitlines()
    else:
        with open(source) as f:
            lines = f.read().strip().splitlines()

    n_declared = 0
    m_declared = 0
    g = WeightedGraph()
    nodes_initialized = False

    for line in lines:
        line = line.strip()
        if not line or line.startswith("c"):
            continue
        parts = line.split()
        if parts[0] == "p":
            # "p edge N M"  of "p col N M"
            if len(parts) < 4:
                continue
            n_declared = int(parts[2])
            m_declared = int(parts[3])
            for i in range(n_declared):
                g.add_node(i)
            nodes_initialized = True
        elif parts[0] == "e":
            if not nodes_initialized:
                raise ValueError("DIMACS: 'e' line vóór 'p' header")
            i = int(parts[1]) - 1
            j = int(parts[2]) - 1
            w = float(parts[3]) if len(parts) >= 4 else 1.0
            if i == j:
                continue
            g.add_edge(i, j, w)
        # else: skip (bv. 'n <vertex> <label>' voor node-labels)

    return g, n_declared, m_declared


def write_dimacs(graph: WeightedGraph, filepath: str, weighted: bool = False) -> None:
    """Schrijf graaf als DIMACS edge-format."""
    edges = list(graph.edges())
    with open(filepath, "w") as f:
        f.write(f"c DIMACS edge-format (generated by b154_dimacs_loader)\n")
        f.write(f"p edge {graph.n_nodes} {len(edges)}\n")
        for i, j, w in edges:
            if weighted:
                f.write(f"e {i+1} {j+1} {w:g}\n")
            else:
                f.write(f"e {i+1} {j+1}\n")


# ============================================================
# 2. DIMACS chromatic database
# ============================================================

# Bron: Johnson & Trick (1996) DIMACS-II resultaten + latere updates.
# Format: {naam: (n, m, χ(G))}
DIMACS_CHROMATIC: dict[str, tuple[int, int, int]] = {
    "myciel3":      (11,    20,   4),
    "myciel4":      (23,    71,   5),
    "myciel5":      (47,   236,   6),
    "myciel6":      (95,   755,   7),
    "myciel7":      (191, 2360,   8),
    "queen5_5":     (25,   160,   5),
    "queen6_6":     (36,   290,   7),
    "queen7_7":     (49,   476,   7),
    "queen8_8":     (64,   728,   9),
    "huck":         (74,   301,  11),
    "jean":         (80,   254,  10),
    "david":        (87,   406,  11),
    "anna":         (138,  493,  11),
    "miles250":     (128,  387,   8),
    "miles500":     (128, 1170,  20),
    "games120":     (120,  638,   9),
    "le450_5a":     (450, 5714,   5),
    "le450_15b":    (450, 8169,  15),
    "petersen":     (10,    15,   3),
    "homer":        (561, 1629,  13),
}


# ============================================================
# 3. Max-k-Cut bounds en reductie naar MaxCut
# ============================================================

def max_k_cut_upper_bound(graph: WeightedGraph, k: int) -> float:
    """Triviale UB: Max-k-Cut ≤ m (alle edges gesnijd als χ(G) ≤ k).

    Preciezer: voor ongewogen graaf geeft een random k-partitie verwachting
    m · (1 − 1/k). Frieze-Jerrum geeft α_k · m met α_k → 1 als k → ∞:
        α_2 ≈ 0.87856, α_3 ≈ 0.83276, α_4 ≈ 0.85022, α_5 ≈ 0.87693.

    Als χ(G) ≤ k, dan is Max-k-Cut = totaal edge-gewicht (alle edges gesnijd).
    """
    return float(graph.total_weight())


def frieze_jerrum_lower_bound(graph: WeightedGraph, k: int) -> float:
    """Frieze-Jerrum gegarandeerde approximatie ondergrens voor Max-k-Cut."""
    alpha_table = {2: 0.87856, 3: 0.83276, 4: 0.85022, 5: 0.87693}
    alpha = alpha_table.get(k, 1.0 - 1.0 / k)  # val terug op random-bound
    return alpha * graph.total_weight()


def dimacs_to_maxcut(graph: WeightedGraph) -> WeightedGraph:
    """Trivial identity: DIMACS unweighted edge-graph = MaxCut input met w=1.

    (De ware Max-k-Cut → MaxCut reductie via de k-expansion-gadget is polynoom
    maar vergroot |V| met factor k. Voor k=2 is het gewoon de identiteit.)
    """
    g_out = WeightedGraph()
    for v in graph.nodes:
        g_out.add_node(v)
    for i, j, w in graph.edges():
        g_out.add_edge(i, j, w)
    return g_out


# ============================================================
# 4. Kleine DIMACS-fixtures als strings
# ============================================================

DIMACS_FIXTURES: dict[str, str] = {
    "petersen": """c Petersen graph in DIMACS edge-format
p edge 10 15
e 1 2
e 2 3
e 3 4
e 4 5
e 5 1
e 6 8
e 8 10
e 10 7
e 7 9
e 9 6
e 1 6
e 2 7
e 3 8
e 4 9
e 5 10
""",
    "myciel3": """c Mycielski graph M_3, chi=4
p edge 11 20
e 1 2
e 1 4
e 1 7
e 1 9
e 2 3
e 2 6
e 2 8
e 3 5
e 3 7
e 3 10
e 4 5
e 4 6
e 4 10
e 5 8
e 5 9
e 6 11
e 7 11
e 8 11
e 9 11
e 10 11
""",
    "queen5_5": """c Queen 5x5 graph (partial; gebruik parse_dimacs)
p edge 6 9
e 1 2
e 2 3
e 3 4
e 4 5
e 5 6
e 1 3
e 2 4
e 3 5
e 4 6
""",
    "k4": """c Complete graph K_4
p edge 4 6
e 1 2
e 1 3
e 1 4
e 2 3
e 2 4
e 3 4
""",
    "c6": """c Cycle C_6
p edge 6 6
e 1 2
e 2 3
e 3 4
e 4 5
e 5 6
e 6 1
""",
}


def load_fixture(name: str) -> tuple[WeightedGraph, int, int]:
    """Laad een ingebouwde kleine DIMACS-graaf."""
    if name not in DIMACS_FIXTURES:
        raise ValueError(f"Onbekende fixture: {name}. Beschikbaar: {list(DIMACS_FIXTURES)}")
    return parse_dimacs(DIMACS_FIXTURES[name], from_text=True)


# ============================================================
# 5. CLI
# ============================================================

def _main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="Toon ingebouwde fixtures + DIMACS-DB")
    ap.add_argument("--file", type=str, default=None, help="Laad DIMACS-file")
    ap.add_argument("--fixture", type=str, default=None, help="Laad ingebouwde fixture (petersen, k4, ...)")
    ap.add_argument("--k", type=int, default=2, help="k voor Max-k-Cut UB (default 2)")
    ap.add_argument("--write", type=str, default=None, help="Schrijf DIMACS-output")
    args = ap.parse_args()

    if args.list:
        print("DIMACS fixtures (inline):")
        for name in DIMACS_FIXTURES:
            print(f"  {name}")
        print()
        print(f"DIMACS chromatic-DB: {len(DIMACS_CHROMATIC)} instanties")
        for name, (n, m, chi) in sorted(DIMACS_CHROMATIC.items()):
            print(f"  {name:<15s} n={n:4d}  m={m:5d}  χ={chi}")
        return

    g = None
    name = ""
    if args.file:
        g, n_decl, m_decl = parse_dimacs(args.file)
        name = os.path.splitext(os.path.basename(args.file))[0]
    elif args.fixture:
        g, n_decl, m_decl = load_fixture(args.fixture)
        name = args.fixture
    else:
        ap.print_help()
        return

    print(f"DIMACS graph: {name}")
    print(f"  declared: n={n_decl}, m={m_decl}")
    print(f"  parsed:   n={g.n_nodes}, m={g.n_edges}, total_w={g.total_weight():g}")

    ub = max_k_cut_upper_bound(g, args.k)
    lb = frieze_jerrum_lower_bound(g, args.k)
    print(f"  Max-{args.k}-Cut UB (= total weight, tight als χ≤{args.k}): {ub:g}")
    print(f"  Frieze-Jerrum LB (α_{args.k} · m): {lb:.2f}")

    if name in DIMACS_CHROMATIC:
        _, _, chi = DIMACS_CHROMATIC[name]
        print(f"  χ(G) = {chi}  (dus Max-{chi}-Cut = m = {g.n_edges})")

    if args.write:
        write_dimacs(g, args.write)
        print(f"  written to: {args.write}")


if __name__ == "__main__":
    _main()
